### ISSUE TITLE
Visual customizations

### ISSUE THREAD

**Issue by JustCallMeQuincy** [Sandakan/Nora#116]
**Is your feature request related to a problem? Please describe.**
I've been thinking about possible ways to implement customization into the 2 themes, since that would - in my opinion - improve overall looks.
First off, an "All-black" dark mode would be awesome.
Also, I'm not sure how handy it is to have the theme selector button constantly showing. It may clean up the look a bit if it's only visible within the settings.
![image](https://user-images.githubusercontent.com/71931404/221393122-abe88226-967c-4a40-b46b-255d0ea7715c.png)

For themes, I have 2 ideas at the moment:

**Idea 1: Preset themes**
![image](https://user-images.githubusercontent.com/71931404/221392393-d9620710-f876-40f6-8e23-87461b1f4768.png)
Could include a palette of colors for both light and dark mode.

**Idea 2: Setting accent color** (This seems more interesting)
The ability to pick the light and dark theme are separate.
Below it could be a selection of colors (or even hex palette) to set the accent color(s) within the app.

(Example:)
![image](https://user-images.githubusercontent.com/71931404/221392504-cdf60ced-0903-4013-bd7a-8ca0c6aafadc.png)

The accent color(s) would affect (not limited to) the following things:
![image](https://user-images.githubusercontent.com/71931404/221393190-48808c02-c558-4459-8291-3a98b5024350.png)
![image](https://user-images.githubusercontent.com/71931404/221393196-5f744f51-3558-41d6-8cbe-69a36642a6c9.png)
![image](https://user-images.githubusercontent.com/71931404/221393248-837be79c-25b9-4382-99c2-cbdf5faf5ddf.png)
![image](https://user-images.githubusercontent.com/71931404/221393252-066334f5-f473-4881-891f-4b5a0120a0c3.png)

The rest of the buttons could also follow this, or maybe take on a faded version of the chosen color.

**Comment by Sandakan** [comment]
I added the 'change theme' button to the title bar so that it would be easy to see the output of the app in different themes when I'm building the app.
I think it's useless to see it every time in the production builds. Thanks for pointing it out.
Maybe I can reserve that space for indicators like the network indicator of the new update indicator.

**Comment by Sandakan** [comment]
Both of your ideas for the themes are hard to achieve in this app due to the way I built it.

I use TailwindCSS for styling the interface of the app and I don't know how to give the user the facility to change the accent colors of the app let alone add different styles for the app since it could drastically complicate how the app's UI is displaying and will lead to a lot of contrast issues and incorrect colors like in #115.
If I was using pure CSS for this, I could have used CSS variables for this feature but I think migrating to pure CSS just for this purpose isn't worth the simplicity I get when using TailwindCSS. 

I'll think about another way that I could achieve this without migrating to pure CSS but I can't promise anything about this feature.
