### ISSUE TITLE
m4a and other format support?

### ISSUE THREAD

**Issue by KazuyaShush** [Sandakan/Nora#130]
i use m4a for my music files and was wondering if that format would be supported in future updates, huge fan of the ui and the oto music inpiration.
Thnaks

**Comment by Sandakan** [comment]
Audio format support purely depends on the formats supported by the HTML5 Audio API. Currently, it supports
- mp3
- ogg
- wav
- aac
- m4r
- flac

Although the app support mp3, ogg, and wav, currently full support (playback, editing tags) is only for mp3.
I didn't add other formats because they lack even more support from packages used by the app.

I don't think you will be able to play m4a format on the app until the audio API supports it or if I decide to migrate to a package like Howler but both won't be happening anytime soon. Sorry for the inconvenience.
