### ISSUE TITLE
Arrowkeys for music controls

### ISSUE THREAD

**Issue by JustCallMeQuincy** [Sandakan/Nora#132]
**Feature**
When the music player is focused (normal and mini player), and not typing (searching, editing tags,...) having the ability to:
skip x seconds with ← and → 
adjust volume with ↓ and ↑

**Comment by Sandakan** [comment]
You can do those exact things by holding `Ctrl` with `←` `→` `↓` `↑`. You can learn more about Nora's keyboard shortcuts in the App Shortcuts menu at the bottom of the Settings menu.
But if you mean without the `Ctrl`, then that would cost user accessibility since arrow keys are primarily used for navigation.

**Comment by JustCallMeQuincy** [comment]
I do indeed mean without the `Ctrl`, but I do see how accessibility could be compromised by this. I'll be using it with the `Ctrl`.
No worries at all.
