### ISSUE TITLE
Sub-folder issue and higher parsing times

### ISSUE THREAD

**Issue by Gluneklairo** [Sandakan/Nora#134]
When adding a music folder, the app will add all sub-folders into folder list. Which is inconvenient to manage because of the huge amount of folder I create for seperate albums. And the settings page will be very long to scroll. Only keeping the root folder is the best option.

Windows has its accent color settings, would be nice if Nora can follow Windows accent color or album cover color.

**Comment by Sandakan** [comment]
Are you suggesting only adding the selected folder without sub-folders? If so I could work on that to add a toggle near the button to add the folder.
I am hoping to remove the 'Music Folders' section in Settings because I have added an alternative as Folders in the sidebar.

I tried adding album cover color to Nora as an accent color but the dependency I use to fetch colors from the covers isn't accurate all the time. You can already see this in the Home where some colors on the Recently Added Songs section aren't on the covers.
![image](https://user-images.githubusercontent.com/45460443/224526268-c4d7709a-dbc0-463f-8ed8-da91c7b4b482.png)
The background color should be white but it gives a brownish color. So I dropped that idea.

**Comment by Gluneklairo** [comment]
> Are you suggesting only adding the selected folder without sub-folders? If so I could work on that to add a toggle near the button to add the folder. I am hoping to remove the 'Music Folders' section in Settings because I have added an alternative as Folders in the sidebar.
> 
> I tried adding album cover color to Nora as an accent color but the dependency I use to fetch colors from the covers isn't accurate all the time. You can already see this in the Home where some colors on the Recently Added Songs section aren't on the covers. ![image](https://user-images.githubusercontent.com/45460443/224526268-c4d7709a-dbc0-463f-8ed8-da91c7b4b482.png) The background color should be white but it gives a brownish color. So I dropped that idea.

Yes, that's just what I mean.
And album cover color isn't a big deal but a custom accent color setting would be good (or follow accent color of Windows personalization settings)
This app is already very complete for me : )

**Comment by Crocodile73** [comment]
Yeah the list is long. Scan time for a large library took over 3hrs.

**Comment by Sandakan** [comment]
> Yeah the list is long. Scan time for a large library took over 3hrs.

How many songs do you have in your library?

**Comment by Crocodile73** [comment]
Alot, lol. About 800+ albums

**Comment by Sandakan** [comment]
![image](https://user-images.githubusercontent.com/45460443/224680585-bf634d2a-765b-497e-a3b8-456a1159d6c6.png)

The time to scan the library depends on the no of songs in the folder.
I have around 1500 songs and it took around 30 minutes.

**Comment by Crocodile73** [comment]
To long even for 1500 songs. Normally on other apps, it's well under 10mins for My library.

**Comment by Sandakan** [comment]
Most of the time is used to save the song artworks in a cache. For each song, two artworks are saved. One is in full resolution and the other is in an optimized resolution to improve app performance.

The app used to use only a few minutes for my library. I'll see what I can do.

**Comment by Crocodile73** [comment]
Still to much time, in scanning the library. For version 2, it was faster, but 2hrs 30 mins is way too long.

**Comment by Sandakan** [comment]
@Crocodile73 ,

There are two types of parsing going on.
1. library parsing - quick, shows a notification `Parsing [ ] out of [ ] songs`
2. palette parsing - time taking, shows a notification `Parsing palettes for [ ] out of [ ] songs`

During the first phase, it's harder to use the app because new songs are added to the library. But during the second phase, there's no need to wait for it to complete. You can use the app as normal.

Can you also tell me how many songs are there in your library and how much time Nora took to complete each phase?

**Comment by Sandakan** [comment]
There are around 1600 songs in my library.

In v1.2.0, Nora took around 15-20 mins to parse the whole library, and the app is harder to use during that time because both phases were combined in that release.

But in v2.0, Nora only took around 3-4 mins to parse the songs in the library (without palette parsing) and after that phase, you can use the app as normal. Palette parsing took another 4 mins complete.

**Comment by Crocodile73** [comment]
I never sat for the whole time, i just caught the last part when it finished. I looked in the log, but there does not seem to be an indication when one part started and ended. Yes my library is very large. The drive is an external SSD, and the app is on my main SSD Windows installation. I have 12GB ram and Intel i5. If you compare nora with say musicbee or windows media player uwp, these process my library very quickly. 10-12mins.

**Comment by Sandakan** [comment]
Can you tell me how many songs are there in your library and the size of your library?
You can find the no of songs in your library by hovering over the app stats section in Settings > About

**Comment by Sandakan** [comment]
@Crocodile73,  I'm sorry. I meant the total size of your songs. 

There's a big difference in how Nora operates when compared to Musicbee, Windows Media Player, or Groove Music.
1. They use native APIs to access the filesystem, since Nora is powered by Electron and Electron uses node.js under the hood, Nora is a bit slower than them.
2. They don't save the song artwork when parsing the audio file. They only show song artwork only when the user selects to play the song. Some only save artwork data only as album artworks, therefore less performance overhead when parsing the library.

**Comment by Crocodile73** [comment]
songs data? 14mb
or songs 12.76k
so is it like dopamine music player?

**Comment by Sandakan** [comment]
No, I meant the folder size. My music folder is taking around 10GB of storage for 1600 songs.
Yeah, like dopamine.

**Comment by Crocodile73** [comment]
ok sorry, brain is a little slow today. 115GB
