### ISSUE TITLE
Automatic artist separation

### ISSUE THREAD

**Issue by JustCallMeQuincy** [Sandakan/Nora#140]
### **Feature one:**

The ability to edit an entire folder (or group of songs) in 1 go, requesting the `Search Metadata on Internet` automatically.
This feature could have a fully-automated mode, where it picks the best results, and also a manual mode, where it shows the results for each song one by one, where the user just clicks through it.

For the latter it could perhaps be a list with the songs and metadata, so that bigger groups of songs don't take up too much time, assuming that most results are correct.

### **Feature two:**

Automatic artist separation
Artists that have separation signs in their names (`&`, `/`, `|`, `·`, ...) should be split up into multiple artists, for cataloging purposes.
Whether this should happen automatically or perhaps (like Google Photos has) like "suggestions" which you can apply or ignore, is up to you.

### I think these features would definitely help keep music lists clean while conserving time in cleaning them up.

**Comment by Sandakan** [comment]
### Feature one
Adding this feature could negatively affect some users' experience since some APIs used for this feature uses the same API key for all other users too (Like the Musixmatch API key). It can quickly blacklist the API key and other users won't be able to use that API again. 
Not to mention the performance impact due to the high amount of requests required to complete a single query.

### Feature two
This is a great feature that I've wanted to implement in the app but I kept it for future releases due to the high complexity it brings to the app. I'll see what I can do about this feature.
