### ISSUE TITLE
Bug in Nora

### ISSUE THREAD

**Issue by LandStander27** [Sandakan/Nora#155]
**Describe the bug**
When the app opens F5 is made a global shortcut for just the app and it completly blocks the key F5 in other programs.

**To Reproduce**

1. Open the app
2. Minimize the app and press F5 anywhere else

**Expected behavior**
I am able to use F5 in other programs.

**Log**
`[Thu, 06 Apr 2023 22:07:28 GMT] =  USER REQUESTED RENDERER REFRESH USING GLOBAL SHORTCUT. 
	{"isFocused":false}`

**System Information:**

- OS: Windows 11
- Affected App Version: 1.2

**Additional information**
- You can use something like [this website](http://whatkeyamipressing.com/) to see

**Comment by LandStander27** [comment]
I saw that it was fixed in the last update in the update logs but it's still happening for me.

**Comment by JustCallMeQuincy** [comment]
Doesn't happen for me anymore, though I don't seem to be able to F5 anywhere but the app.

On Windows 10

**Comment by Sandakan** [comment]
I think the bug @JustCallMeQuincy mentioned is the bug that @LandStander27 is also facing. 

`{"isFocused":false}` means that the app is not focused, so the app won't reload the renderer. But since the global shortcut is still registered, the app will handle the event by doing nothing.

Thanks for mentioning the bug. I will fix it in the next update.

**Comment by JustCallMeQuincy** [comment]
Confirmed!
