### ISSUE TITLE
Feature Request: An option to save settings, music stats, playlists ?

### ISSUE THREAD

**Issue by metronightly** [Sandakan/Nora#159]
Updating from 1.2 to 2.0 has caused me to lose all my playlists, nice music stats (lol) and settings (not much but still) 

If possible please provide an option to save this things so that we can update without any data loss.

**Comment by Sandakan** [comment]
Im so sorry to hear that.
This happened because I had to do some unrecoverable modifications to the app database (specifically how the folders are saved).

**Comment by Sandakan** [comment]
You couldn't have done anything to prevent it. Even though you saved every config file, the app would break in the new update if you apply those previous config files.

**Comment by metronightly** [comment]
> You couldn't have done anything to prevent it. Even though you saved every config file, the app would break in the new update if you apply those previous config files. That's why I had to force reset the app.

Oh, that's okay, no worries. So there is a way to save config files to save all stats, playlist and such in the new update? If possible where can I find those files just in case I have to restore a complete backup of Nora ?

**Comment by Sandakan** [comment]
Config files are located in `C:\Users\USER_NAME\AppData\Roaming\Nora`

The main files you could backup are
- userData.json - holds user data. Act as the main point when parsing the library since data related to folders is stored here.
- songs.json - saves data related to songs.
- song_covers folder - saves all the artwork
- artists.json
- albums.json
- genres.json
- playlists.json 
- blacklist.json (optional, if you don't want blacklist info)

But keep in mind that this could negatively impact your experience with the app because this can lead to compatibility issues when paired when newer or older versions. Especially when paired with a major update (copying the config files of the app version 1.2.0 to version 2.0.0.)

**Comment by metronightly** [comment]
> Config files are located in `C:\Users\USER_NAME\AppData\Roaming\Nora`
> 
> The main files you could backup are
> 
>     * userData.json - holds user data. Act as the main point when parsing the library since data related to folders is stored here.
> 
>     * songs.json - saves data related to songs.
> 
>     * song_covers folder - saves all the artwork
> 
>     * artists.json
> 
>     * albums.json
> 
>     * genres.json
> 
>     * playlists.json
> 
>     * blacklist.json (optional, if you don't want blacklist info)
> 
> 
> But keep in mind that this could negatively impact your experience with the app because this can lead to compatibility issues when paired when newer or older versions. Especially when paired with a major update (copying the config files of the app version 1.2.0 to version 2.0.0.)

Awesome, thanks a lot.
