### ISSUE TITLE
Related to #158 - Song bar right-click functionality 

### ISSUE THREAD

**Issue by JustCallMeQuincy** [Sandakan/Nora#160]
Simply said, it would be nice to have similar song options to right-clicking a song in the current queue:
![image](https://user-images.githubusercontent.com/71931404/233847895-b9bd101e-6312-4d78-ab94-5086e5291a6c.png)

Some interesting options would be:

- Like this song
- Add to a playlist
- Reveal in File Explorer
- Edit song tags
- Blacklist Song
- Delete from System

**Comment by metronightly** [comment]
There's the like button there already, so I think that would be redundant but rest of the options would be nice additions. However, in the latest update right clicking on the album cover on the song bar presents three options for now: 
![image](https://user-images.githubusercontent.com/75716685/233850673-308f0f30-b295-4b5c-8ac4-37bd3eb3d4ae.png)

Also a suggestion for Sandakan is to remove "Like the song" option from other right click menus because all of them already have the like button, this way it's cleaner with one less redundant option in the context menu  (right click menu or whatever they are called haha)

**Comment by Sandakan** [comment]
@JustCallMeQuincy are you suggesting adding more options for the context menu when right-clicking the current playing song artwork?

**Comment by Sandakan** [comment]
I don't think that's a good idea.

![234094180-8af8fcf3-04b7-4931-aada-ee297729a71d](https://user-images.githubusercontent.com/45460443/234181382-51fb26bf-8891-467a-bb50-985d3c3cbca9.png)

App footer is divided into 3 parts,
1. Current song info container
2. Song controls container
3. Other controls container

I don't think it would give a good user experience if a context menu was triggered in the whole footer.

But I can focus that context menu on the first container so that users have an idea about what the context menu is focusing on.
