### ISSUE TITLE
Bug in Nora - a javascript error occurred in the main process

### ISSUE THREAD

**Issue by MikeeSierrah** [Sandakan/Nora#195]
Hi - when i run  the app it says error 
![image](https://github.com/Sandakan/Nora/assets/144580664/c6868c8c-3194-4aa9-8429-6acf0749b15f)
no logs because there is none. 
at first, I updated from 2.3 and thought maybe it's from that. 
but no even clean installation didn't help. 

- OS: win 11
- Affected App Version: 2.4 stable

**Comment by Sandakan** [comment]
It happens because you have a custom musixmatch token applied and Nora tries to encrypt it without an encryption secret

A fix you can do is to go to C://Users/USERNAME/AppData/Local/Nora and open the file userData.json and remove the line that contains 'customMusixmatchToken'.

Only modify that line.

I'll send a fix later today.

**Comment by MikeeSierrah** [comment]
thanks, fixed my problem, but the file was in C:\Users\USERNAME\AppData\Roaming\Nora

**Comment by Sandakan** [comment]
> thanks, fixed my problem, but the file was in C:\Users\USERNAME\AppData\Roaming\Nora

Oh, sorry about that

**Comment by RichardKanshen** [comment]
was getting the same error after update, tysm for the fix
